// Regenerate apps/worker/seed.sql, inlining the example agent definition
// as a SQL string literal. Run: node scripts/gen-seed.mjs
import { readFileSync, writeFileSync } from "node:fs";

const def = readFileSync("examples/agents/close-read.json", "utf8");
const sqlString = `'${def.replace(/'/g, "''")}'`;

const sql = `-- seed.sql — minimal data so the app runs end-to-end in local dev.
-- GENERATED by scripts/gen-seed.mjs — edit the agent JSON, not this file.
-- Apply after migrations:  npm run db:seed --workspace apps/worker
-- The DEV_AUTH_EMAIL in wrangler.toml must match the seeded user email.

INSERT OR IGNORE INTO organizations (id, name, created_at)
VALUES ('default', 'Default Org', 0);

INSERT OR IGNORE INTO users (id, org_id, email, display_name, created_at)
VALUES ('user_dev', 'default', 'instructor@example.edu', 'Dev Instructor', 0);

INSERT OR IGNORE INTO courses (id, org_id, name, created_at)
VALUES ('course_demo', 'default', 'Demo Course', 0);

INSERT OR IGNORE INTO enrollments (id, course_id, user_id, role, created_at)
VALUES ('enr_dev', 'course_demo', 'user_dev', 'instructor', 0);

INSERT OR IGNORE INTO agents (id, course_id, title, definition, created_at, updated_at)
VALUES ('agent_close_read', 'course_demo', 'Close-read a primary source', ${sqlString}, 0, 0);
`;

writeFileSync("apps/worker/seed.sql", sql);
console.log("apps/worker/seed.sql written");
